// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'center': string;
  'container': string;
  'reset-button': string;
  'selected-speed-button': string;
  'speed-button': string;
  'start-button': string;
  'tagline': string;
  'time-display': string;
  'timer': string;
  'timer-input': string;
  'timer-input-container': string;
}
export const cssExports: CssExports;
export default cssExports;
